#pragma once

#include <cstdint>
#include <optional>
#include <span>
#include <string_view>

namespace blake3pp {

namespace kern {
struct kernel_ops;
}

/// The instruction-set variants a binary may carry.
///
/// Which ones a binary actually carries is a build-time property
/// (compiled_arches(), cmake/ArchKernels.cmake); which ones are usable is
/// a runtime property of the CPU (available_arches()). auto_detect
/// resolves to the best usable variant. The enumerators, their canonical
/// names and the dispatch preference are generated from one list,
/// detail/arch.def, which documents each entry; its line order is the
/// ABI order and append-only.
enum class arch : std::uint8_t {
  /// Resolves to the best usable variant at runtime.
  auto_detect,
  /// Portable C++ without SIMD; always compiled, the final fallback.
  scalar,
  /// x86-64 SSE4.2, 128-bit lanes.
  sse42,
  /// x86-64 AVX2, 256-bit lanes.
  avx2,
  /// x86-64 AVX-512 (F, CD, VL, BW, DQ), 512-bit lanes.
  avx512,
  /// AArch64 NEON, 128-bit lanes. Architecturally mandatory on AArch64:
  /// presence of the kernel implies availability.
  neon,
};

/// True if the variant is compiled into this binary and the running CPU
/// supports it.
/// @param a  Any variant; auto_detect is always available.
[[nodiscard]] bool is_available(arch a) noexcept;

/// The variant auto_detect resolves to on this machine.
[[nodiscard]] arch best_available() noexcept;

/// The variants compiled into this binary, best-first, always ending with
/// scalar.
///
/// The table is generated by the build from the registered kernels, so a
/// variant appears iff its code is really in the binary.
[[nodiscard]] std::span<const arch> compiled_arches() noexcept;

/// The compiled variants this CPU can run, best-first; never empty, and
/// available_arches().front() == best_available().
[[nodiscard]] std::span<const arch> available_arches() noexcept;

/// The canonical lowercase name of a variant ("auto", "sse42", "avx2").
/// @param a  Any variant.
[[nodiscard]] const char* to_string(arch a) noexcept;

/// The inverse of to_string(): parses a canonical (lowercase) name.
/// @param name  A variant name, as to_string() spells it.
/// @return The variant, or std::nullopt for any other string.
[[nodiscard]] std::optional<arch> arch_from_string(
    std::string_view name) noexcept;

/// Every enumerator (auto_detect first, then best-first) regardless of
/// what is compiled or runnable: the list to build CLIs and menus from,
/// so consumers never hand-enumerate the enum.
[[nodiscard]] std::span<const arch> all_arches() noexcept;

/// The library version, as the library was built (the git-derived
/// stamp; see blake3ppsum --version).
[[nodiscard]] std::string_view version() noexcept;
/// Which SIMD facade backs this build of the library: "std::simd",
/// "std::experimental::simd" or "xsimd".
[[nodiscard]] std::string_view simd_provider() noexcept;
/// Which sender/receiver implementation backs this build of the library:
/// "std::execution" or "stdexec".
[[nodiscard]] std::string_view execution_provider() noexcept;

namespace detail {
// Maps an arch to its kernel table; unavailable variants fall back to the
// best available one. Never returns null.
[[nodiscard]] const kern::kernel_ops* resolve(arch a) noexcept;
}

}  // namespace blake3pp
