#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string_view>

namespace blake3pp {

namespace kern {
struct kernel_ops;
}

/// The instruction-set variants a binary may carry.
///
/// Which ones a binary actually carries is a build-time property
/// (compiled_arches(), cmake/ArchKernels.cmake); which ones are usable is
/// a runtime property of the CPU (available_arches()). auto_detect
/// resolves to the best usable variant. The enumerators, their canonical
/// names and the dispatch preference are generated from one list,
/// detail/arch.def, which documents each entry; its line order is the
/// ABI order and append-only.
enum class arch : std::uint8_t {
  /// Resolves to the best usable variant at runtime.
  auto_detect,
  /// Portable C++ without SIMD; always compiled, the final fallback.
  scalar,
  /// x86-64 SSE4.2, 128-bit lanes.
  sse42,
  /// x86-64 AVX2, 256-bit lanes.
  avx2,
  /// x86-64 AVX-512 (F, CD, VL, BW, DQ), 512-bit lanes.
  avx512,
  /// AArch64 NEON, 128-bit lanes. Architecturally mandatory on AArch64:
  /// presence of the kernel implies availability.
  neon,
  /// WebAssembly SIMD128. A module-level feature: an engine that lacks it
  /// rejects the whole module at load, so if this code is running at all,
  /// the variant is available.
  simd128,
  /// AArch64 SVE at a vector length of exactly 128 bits (opt-in build).
  sve128,
  /// AArch64 SVE at exactly 256 bits (Neoverse V1 / Graviton3 class).
  sve256,
  /// AArch64 SVE at exactly 512 bits (Fujitsu A64FX class).
  sve512,
  /// AArch64 SVE2 at exactly 128 bits, with the XAR fused xor-rotate
  /// (Neoverse N2/V2, Grace, Graviton4).
  sve2_128,
  /// AArch64 SVE2 at exactly 256 bits (opt-in build).
  sve2_256,
  /// AArch64 SVE2 at exactly 512 bits (opt-in build).
  sve2_512,
  /// RISC-V RVV 1.0 at a vector length of exactly 128 bits.
  rvv128,
  /// RISC-V RVV 1.0 at exactly 256 bits.
  rvv256,
  /// RISC-V RVV 1.0 at exactly 512 bits.
  rvv512,
};

/// True if the variant is compiled into this binary and the running CPU
/// supports it.
/// @param a  Any variant; auto_detect is always available.
[[nodiscard]] bool is_available(arch a) noexcept;

/// The variant auto_detect resolves to on this machine.
[[nodiscard]] arch best_available() noexcept;

/// The variants compiled into this binary, best-first, always ending with
/// scalar.
///
/// The table is generated by the build from the registered kernels, so a
/// variant appears iff its code is really in the binary.
[[nodiscard]] std::span<const arch> compiled_arches() noexcept;

/// The compiled variants this CPU can run, best-first; never empty, and
/// available_arches().front() == best_available().
[[nodiscard]] std::span<const arch> available_arches() noexcept;

/// The canonical lowercase name of a variant ("auto", "sse42", "avx2").
/// @param a  Any variant.
[[nodiscard]] const char* to_string(arch a) noexcept;

/// The inverse of to_string(): parses a canonical (lowercase) name.
/// @param name  A variant name, as to_string() spells it.
/// @return The variant, or std::nullopt for any other string.
[[nodiscard]] std::optional<arch> arch_from_string(
    std::string_view name) noexcept;

/// Every enumerator (auto_detect first, then best-first) regardless of
/// what is compiled or runnable: the list to build CLIs and menus from,
/// so consumers never hand-enumerate the enum.
[[nodiscard]] std::span<const arch> all_arches() noexcept;

/// The library version, as the library was built (the git-derived
/// stamp; see blake3ppsum --version).
[[nodiscard]] std::string_view version() noexcept;
/// Which SIMD facade backs this build of the library: "std::simd",
/// "std::experimental::simd" or "xsimd".
[[nodiscard]] std::string_view simd_provider() noexcept;
/// Which sender/receiver implementation backs this build of the library:
/// "std::execution", "beman.execution" or "stdexec".
[[nodiscard]] std::string_view execution_provider() noexcept;

/// The strategy for the 16-lane message transpose used by every width-16
/// kernel (avx512, sve512/sve2_512, rvv512).
///
/// The right choice depends on the execution datapath (full-width or
/// double-pumped), which no CPUID bit reports, and on where the input
/// lives; it moves about 10% and is not predictable from the CPU alone.
/// Two AMD parts with identical feature flags rank the strategies in
/// opposite order at the same input size (Strix Point: quartered 17% over
/// staging; Strix Halo: staging 8% over quartered), and on one machine
/// the winner changes with the input (Strix Halo: quartered for an 8 MiB
/// input that fits in cache, staging for a 512 MiB one streaming from
/// DRAM). All numbers are AVX-512 measurements, the only width-16
/// hardware measured so far.
///
/// The three cost policies, none of them implicit:
///   - Do nothing: quartered, the default, measured best on most parts
///     tested and never worse than about 10% off.
///   - Tune per start: tune_transpose16(bytes) races the strategies on
///     this CPU over a working set the size of the typical input,
///     applies the winner process-wide and returns it.
///   - Tune once ever: persist to_string(tune_transpose16(bytes)) and on
///     later starts restore with
///     set_transpose16(transpose16_from_string(saved).value_or(
///         transpose16::quartered)).
/// Workloads at the edge measure themselves with blake3pp_bench (the
/// t16-* rows and --t16-sweep) and pin the winner with set_transpose16().
/// On machines without a width-16 kernel the setting is inert. Thread-safe;
/// switching mid-hash is benign, since every strategy is correct.
enum class transpose16 : std::uint8_t {
  staging = 0,    ///< Scalar gather through a staging array.
  tree = 1,       ///< Radix-2 register shuffle network.
  quartered = 2,  ///< 128-bit insert-loads plus in-lane unpacks (the default).
};
/// Pins the transpose strategy process-wide.
/// @param strategy  The strategy every width-16 kernel uses from now on.
void set_transpose16(transpose16 strategy) noexcept;
/// The strategy currently in effect.
[[nodiscard]] transpose16 active_transpose16() noexcept;

/// The working set tune_transpose16() races over when given no size:
/// large enough to stream past the last-level cache of current parts,
/// the regime of this library's headline workload (hashing files).
/// Callers who hash something smaller should say so.
inline constexpr std::size_t default_tune_bytes = 128u << 20;
/// Races the transpose strategies on this CPU and applies the winner
/// process-wide.
///
/// Never called implicitly. Costs one streaming pass per strategy (tens of
/// milliseconds for small inputs, a few hundred at the 256 MiB cap) and
/// allocates a buffer of that size. A no-op returning the active strategy
/// where no width-16 kernel is available.
/// @param typical_input_bytes  The size the application actually hashes;
///                             the answer depends on it.
/// @return The winning strategy, now active.
transpose16 tune_transpose16(std::size_t typical_input_bytes) noexcept;
/// Races the transpose strategies over default_tune_bytes and applies the
/// winner process-wide.
/// @return The winning strategy, now active.
transpose16 tune_transpose16() noexcept;
/// The canonical name of a strategy ("staging", "tree", "quartered").
/// @param strategy  Any strategy.
[[nodiscard]] std::string_view to_string(transpose16 strategy) noexcept;
/// The inverse of to_string(): parses a strategy name.
/// @param name  A name as to_string() spells it.
/// @return The strategy, or std::nullopt for any other string.
[[nodiscard]] std::optional<transpose16> transpose16_from_string(
    std::string_view name) noexcept;

namespace detail {
// Maps an arch to its kernel table; unavailable variants fall back to the
// best available one. Never returns null.
[[nodiscard]] const kern::kernel_ops* resolve(arch a) noexcept;
}

}  // namespace blake3pp
