# Cross toolchain: ppc64le Linux, GCC 15, C++23. Executables run through
# qemu-user (CROSSCOMPILING_EMULATOR); qemu selects the CPU generation via
# QEMU_CPU (power8/power9/power10), which drives the vsx dispatch matrix
# from one build; the same emulator-in-the-loop pattern as aarch64/riscv64.
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# native-compiler matrix): cross toolchains carry target/emulator plumbing
# the generator does not model.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ppc64le)

set(CMAKE_C_COMPILER powerpc64le-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER powerpc64le-linux-gnu-g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-ppc64le;-L;/usr/powerpc64le-linux-gnu")

set(CMAKE_FIND_ROOT_PATH /usr/powerpc64le-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Same reasoning as the riscv64 toolchain: libstdc++ has no VSX
# experimental::simd ABI worth trusting, and the vsx kernel pins xsimd
# anyway; stating it explicitly keeps simd_provider() truthful.
set(BLAKE3PP_SIMD_PROVIDER "xsimd" CACHE STRING
  "simd provider (set by the ppc64le toolchain)")
