# Cross toolchain: riscv64 Linux, GCC 15, C++23. Executables run through
# qemu-user (ctest picks this up via CROSSCOMPILING_EMULATOR), whose RVV 1.0
# emulation has a selectable VLEN (QEMU_CPU=max,vlen=<bits>), so the whole
# fixed-VLEN rvv dispatch matrix runs from one build, the same
# emulator-in-the-loop pattern the aarch64 preset uses for SVE.
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# native-compiler matrix): cross toolchains carry target/emulator plumbing
# the generator does not model.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER riscv64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-linux-gnu-g++)

# Ubuntu resolute's riscv64 gcc defaults to the RVA23 profile baseline:
# V, Zvbb and friends emitted unconditionally. Left alone, that plants
# ungated vector code in every non-kernel TU (GCC autovectorizes
# mimalloc's random-init into Zvbb vwsll, which SIGILLs before main on
# anything below RVA23). Pin the BASE build to plain rv64gc; kernel
# TUs opt into their extensions per-TU via ARCH_FLAGS, which append
# after these and win.
set(CMAKE_C_FLAGS_INIT "-march=rv64gc")
set(CMAKE_CXX_FLAGS_INIT "-march=rv64gc")

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-riscv64;-L;/usr/riscv64-linux-gnu")

set(CMAKE_FIND_ROOT_PATH /usr/riscv64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# libstdc++ has no RVV ABI: the experimental::simd probe would pass with a
# generic (scalar-progress) native_simd, so "auto" would pick a provider
# that cannot vectorize here while the rvv kernel TUs pin xsimd anyway.
# Saying xsimd out loud keeps simd_provider() introspection truthful and
# the base build consistent with what the kernels actually use.
set(BLAKE3PP_SIMD_PROVIDER "xsimd" CACHE STRING
  "simd provider (set by the riscv64 toolchain: no std RVV ABI exists)")
