# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# GCC 16 with libstdc++ 16, C++26
#
#   cmake -S . -B build/linux-gcc16-cxx26 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-gcc16-cxx26/linux-gcc16-cxx26.cmake


set(TC_C_COMPILER "gcc-16")
set(TC_CXX_COMPILER "g++-16")
set(TC_CXX_STANDARD "26")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/../common.cmake")
