# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 20 against libstdc++ 14 (pinned), C++23
#
#   cmake -S . -B build/linux-clang20-cxx23-libstdcxx -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang20-cxx23-libstdcxx.cmake


set(TC_C_COMPILER "clang-20")
set(TC_CXX_COMPILER "clang++-20")
set(TC_STDLIB "libstdc++")
set(TC_GCC_INSTALL_DIR "/usr/lib/gcc/x86_64-linux-gnu/14")
set(TC_CXX_STANDARD "23")
set(TC_LINKER "lld-20")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
