# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 22 with libc++, experimental -std=c++2d
#
#   cmake -S . -B build/linux-clang22-cxx2d -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang22-cxx2d.cmake


set(TC_C_COMPILER "clang-22")
set(TC_CXX_COMPILER "clang++-22")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD_RAW "c++2d")
set(TC_LINKER "lld-22")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
