# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# GCC 12 with libstdc++ 12, C++20
#
#   cmake -S . -B build/linux-gcc12-cxx20 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-gcc12-cxx20.cmake


set(TC_C_COMPILER "gcc-12")
set(TC_CXX_COMPILER "g++-12")
set(TC_CXX_STANDARD "20")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
