# Cross toolchain: aarch64 Linux, GCC 15, C++23. Executables run through
# qemu-user (ctest picks this up via CROSSCOMPILING_EMULATOR), so the whole
# test suite executes the NEON kernel in-container. This is the same
# emulator-in-the-loop trick SDE provides for AVX-512, with the twist that
# qemu's NEON support is complete where its AVX-512 is absent.
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# native-compiler matrix): cross toolchains carry target/emulator plumbing
# the generator does not model.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-aarch64;-L;/usr/aarch64-linux-gnu")

set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
