# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 22 with libc++ 22, C++26 + msan
#
#   cmake -S . -B build/linux-clang22-cxx26-msan -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang22-cxx26-msan.cmake


set(TC_C_COMPILER "clang-22")
set(TC_CXX_COMPILER "clang++-22")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_LINKER "lld-22")
set(TC_DEFAULT_BUILD_TYPE "Debug")
set(TC_SANITIZERS memory)
set(TC_MSAN_LIBCXX_PREFIX "/opt/libcxx-msan")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
