# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 20 with libc++ (system), C++26
#
#   cmake -S . -B build/linux-clang20-cxx26 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang20-cxx26.cmake


set(TC_C_COMPILER "clang-20")
set(TC_CXX_COMPILER "clang++-20")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_LINKER "lld-20")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
