# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 22 with libc++ (system), C++26 + tsan
#
#   cmake -S . -B build/linux-clang22-cxx26-tsan -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang22-cxx26-tsan.cmake


set(TC_C_COMPILER "clang-22")
set(TC_CXX_COMPILER "clang++-22")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_LINKER "lld-22")
set(TC_DEFAULT_BUILD_TYPE "Debug")
set(TC_SANITIZERS thread)

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
