# Cross toolchain: s390x Linux, GCC 15, C++23. The project's first
# BIG-ENDIAN target. Executables run through qemu-user
# (CROSSCOMPILING_EMULATOR); QEMU_CPU selects the machine generation
# (qemu's default/max carries the z14 vector-enhancements facility, and
# an older model runs the scalar fallback).
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers
# the native-compiler matrix).

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR s390x)

set(CMAKE_C_COMPILER s390x-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER s390x-linux-gnu-g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-s390x;-L;/usr/s390x-linux-gnu")

set(CMAKE_FIND_ROOT_PATH /usr/s390x-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Same reasoning as riscv64/ppc64le: the vxe kernel pins xsimd; keep the
# base build and the introspection consistent with it.
set(BLAKE3PP_SIMD_PROVIDER "xsimd" CACHE STRING
  "simd provider (set by the s390x toolchain)")
