# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 22 against libstdc++ 16 (pinned), C++23
#
#   cmake -S . -B build/linux-clang22-cxx23-libstdcxx -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang22-cxx23-libstdcxx.cmake


set(TC_C_COMPILER "clang-22")
set(TC_CXX_COMPILER "clang++-22")
set(TC_STDLIB "libstdc++")
set(TC_GCC_INSTALL_DIR "/usr/lib/gcc/x86_64-linux-gnu/16")
set(TC_CXX_STANDARD "23")
set(TC_LINKER "lld-22")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
