# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# GCC 14 with libstdc++ 14, C++26
#
#   cmake -S . -B build/linux-gcc14-cxx26 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-gcc14-cxx26.cmake


set(TC_C_COMPILER "gcc-14")
set(TC_CXX_COMPILER "g++-14")
set(TC_CXX_STANDARD "26")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
