# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 18 with libc++ 18, C++20
#
#   cmake -S . -B build/linux-clang18-cxx20 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang18-cxx20.cmake


set(TC_C_COMPILER "clang-18")
set(TC_CXX_COMPILER "clang++-18")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "20")
set(TC_LINKER "lld-18")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
