# Homebrew LLVM 22 on macOS, C++26: the Darwin twin of linux-clang22-cxx26
# (same clang major, same libc++, same providers: xsimd + stdexec).
#
#   cmake -S . -B build/macos-clang22-cxx26 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/macos-clang22-cxx26.cmake
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# Linux native-compiler matrix): the Homebrew keg is keg-only and its libc++
# needs explicit link plumbing the generator does not model.
#
# Homebrew's clang uses its OWN libc++ headers automatically (and its clang
# config file already points -isysroot at the CommandLineTools SDK), but at
# link time ld64 would resolve -lc++ against the SDK's stub for the SYSTEM
# libc++: headers newer than the library, the classic keg-only mismatch.
# Per the formula's caveats: link the bundled libc++/libunwind explicitly
# (plus rpaths so the binaries run without DYLD_* help), and define
# _LIBCPP_DISABLE_AVAILABILITY so availability markup keyed to macOS system
# libc++ versions does not hide features libc++ 22 actually ships.

set(_brew_llvm "/opt/homebrew/opt/llvm")
if(NOT IS_DIRECTORY "${_brew_llvm}")
  set(_brew_llvm "/usr/local/opt/llvm")  # Intel-Mac Homebrew prefix
endif()
if(NOT IS_DIRECTORY "${_brew_llvm}")
  message(FATAL_ERROR "toolchain: no Homebrew LLVM found (brew install llvm)")
endif()

set(TC_C_COMPILER "${_brew_llvm}/bin/clang")
set(TC_CXX_COMPILER "${_brew_llvm}/bin/clang++")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

set(TC_EXTRA_CXX_FLAGS "-D_LIBCPP_DISABLE_AVAILABILITY")
set(TC_EXTRA_LINK_FLAGS
  "-L${_brew_llvm}/lib/c++"
  "-Wl,-rpath,${_brew_llvm}/lib/c++"
  "-L${_brew_llvm}/lib/unwind"
  "-Wl,-rpath,${_brew_llvm}/lib/unwind"
  "-lunwind")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
