# Homebrew LLVM 22 on macOS, C++26: the Darwin twin of linux-clang22-cxx26
# (same clang major, same libc++, same providers: xsimd + stdexec).
#
#   cmake -S . -B build/macos-clang22-cxx26 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/macos-clang22-cxx26.cmake
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# Linux native-compiler matrix): the Homebrew keg is keg-only and its libc++
# needs explicit link plumbing the generator does not model.
#
# Homebrew's clang uses its OWN libc++ headers automatically (and its clang
# config file already points -isysroot at the CommandLineTools SDK), but at
# link time ld64 would resolve -lc++ against the SDK's stub for the SYSTEM
# libc++: headers newer than the library, the classic keg-only mismatch.
# Per the formula's caveats: link the bundled libc++/libunwind explicitly
# (plus rpaths so the binaries run without DYLD_* help), and define
# _LIBCPP_DISABLE_AVAILABILITY so availability markup keyed to macOS system
# libc++ versions does not hide features libc++ 22 actually ships.

# The preset is pinned to clang 22 (its identity is being the Darwin twin
# of linux-clang22-cxx26), so accept the versioned keg or an unversioned
# `llvm` that still resolves to a 22.x Cellar, never a different major
# silently wearing the preset's name. The GitHub macos runner images
# preinstall only a versioned OLDER keg (llvm@18 on macos-15) and
# Homebrew's unversioned formula has moved past 22, which is why this
# preset is a local-Mac preset, not a CI lane (see the macos job comment
# in ci.yml): brew install llvm@22 first.
set(_brew_llvm "")
foreach(_prefix "/opt/homebrew/opt" "/usr/local/opt")  # arm64 / Intel-Mac
  foreach(_keg "llvm@22" "llvm")
    if(IS_DIRECTORY "${_prefix}/${_keg}")
      # opt/<keg> links to Cellar/<formula>/<version>; check the major.
      get_filename_component(_brew_llvm_real "${_prefix}/${_keg}" REALPATH)
      get_filename_component(_brew_llvm_ver "${_brew_llvm_real}" NAME)
      if(_brew_llvm_ver MATCHES "^22(\\.|$)")
        set(_brew_llvm "${_prefix}/${_keg}")
        break()
      endif()
    endif()
  endforeach()
  if(_brew_llvm)
    break()
  endif()
endforeach()
if(NOT _brew_llvm)
  message(FATAL_ERROR "toolchain: no Homebrew LLVM 22 found (brew install llvm@22)")
endif()

set(TC_C_COMPILER "${_brew_llvm}/bin/clang")
set(TC_CXX_COMPILER "${_brew_llvm}/bin/clang++")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

set(TC_EXTRA_CXX_FLAGS "-D_LIBCPP_DISABLE_AVAILABILITY")
set(TC_EXTRA_LINK_FLAGS
  "-L${_brew_llvm}/lib/c++"
  "-Wl,-rpath,${_brew_llvm}/lib/c++"
  "-L${_brew_llvm}/lib/unwind"
  "-Wl,-rpath,${_brew_llvm}/lib/unwind"
  "-lunwind")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
