# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# GCC 16 with libstdc++ 16, C++23
#
#   cmake -S . -B build/linux-gcc16-cxx23 -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-gcc16-cxx23/linux-gcc16-cxx23.cmake


set(TC_C_COMPILER "gcc-16")
set(TC_CXX_COMPILER "g++-16")
set(TC_CXX_STANDARD "23")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/../common.cmake")
