# Cross toolchain: mips64el Linux, GCC 14, C++23. Executables run through
# qemu-user (CROSSCOMPILING_EMULATOR), the same emulator-in-the-loop
# pattern as aarch64/riscv64/ppc64le, and here it is the ONLY way this
# target is ever exercised: no MSA silicon is reachable, so every number
# from this lane is a qemu number and only its digests mean anything.
#
# GCC 14 rather than 15 because Debian packages no newer mips64el cross;
# the lane therefore runs the Parallelism TS rather than C++26 <simd>,
# which costs nothing here since the msa kernel pins the vector-extension
# provider anyway (see _blake3pp_register_mips_kernels).
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers the
# native-compiler matrix): cross toolchains carry target/emulator plumbing
# the generator does not model.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips64el)

set(CMAKE_C_COMPILER mips64el-linux-gnuabi64-gcc)
set(CMAKE_CXX_COMPILER mips64el-linux-gnuabi64-g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# Resolved to an absolute path: under cmake-re the test launcher
# (tipi-test-driver) execve's the command literally, no PATH search.
find_program(BLAKE3PP_QEMU NAMES qemu-mips64el REQUIRED NO_CACHE)
set(CMAKE_CROSSCOMPILING_EMULATOR
    "${BLAKE3PP_QEMU};-L;/usr/mips64el-linux-gnuabi64")

set(CMAKE_FIND_ROOT_PATH /usr/mips64el-linux-gnuabi64)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# The msa kernel pins the vector-extension provider regardless; this
# states the project-wide answer so simd_provider() stays truthful.
set(BLAKE3PP_SIMD_PROVIDER "std-experimental" CACHE STRING
  "simd provider (set by the mips64el toolchain)")
