# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 22 with libc++ (system), C++26 + asan
#
#   cmake -S . -B build/linux-clang22-cxx26-asan -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/linux-clang22-cxx26-asan/linux-clang22-cxx26-asan.cmake


set(TC_C_COMPILER "clang-22")
set(TC_CXX_COMPILER "clang++-22")
set(TC_STDLIB "libc++")
set(TC_CXX_STANDARD "26")
set(TC_LINKER "lld-22")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")
set(TC_SANITIZERS address undefined)

include("${CMAKE_CURRENT_LIST_DIR}/../common.cmake")
