#!/usr/bin/env python3
"""Generate self-contained CMake toolchain files for the whole matrix.

Each emitted file sets a few TC_* variables and includes common.cmake, so a
consumer only ever needs:

    cmake -S . -B build/<name> -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/<name>.cmake

Run once and commit the result:

    python3 tools/gen-toolchains.py
    python3 tools/gen-toolchains.py --all          # every instrumentation everywhere
    python3 tools/gen-toolchains.py --list         # names only, no writing
    python3 tools/gen-toolchains.py --presets      # also emit CMakePresets fragment

Names match the CMake preset names one-for-one, so the two systems stay in sync.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUTDIR_DEFAULT = os.path.join(REPO, "cmake", "toolchains")

# --- edit these to match your image ----------------------------------------
GCC_VERSIONS = [14, 16]
CLANG_VERSIONS = [18, 20, 22]

# Which standards make sense per compiler. GCC gained -std=c++26 in GCC 14;
# Clang has spelled it c++2c since 17 (CMake picks the right spelling for you
# when you use CMAKE_CXX_STANDARD, which is what these files do).
GCC_STDS = {14: [23, 26], 16: [23, 26]}
CLANG_STDS = {18: [20, 23], 20: [23, 26], 22: [23, 26]}

# The triple normally lives under /usr/lib/gcc/<triple>/<ver>.
GCC_TRIPLE = "x86_64-linux-gnu"

# Names are <os>-<compiler><ver>-cxx<std>[-variant]. This generator emits the
# LINUX native-compiler matrix only; the macOS and Windows toolchains are
# hand-written (Homebrew keg-only libc++ plumbing, vcvars) and say so at the
# top of each file. So the OS component is a fixed default, NOT the host:
# sniffing sys.platform meant a run from a Mac silently emitted a macos-*
# matrix and overwrote those hand-written files. Override with --os only if
# you are deliberately generating another OS's matrix.
HOST_OS = "linux"

DEFAULT_GCC = 16
DEFAULT_CLANG = 22

# Which GCC's libstdc++ a given Clang can realistically parse. Roughly "the GCC
# released around the same time" -- a Clang reading headers from a much newer
# libstdc++ trips over built-ins it does not implement. Falls back to
# clang_version - 6 for anything not listed. Adjust if you hit a bad pair.
CLANG_TO_GCC = {17: 14, 18: 14, 19: 14, 20: 15, 21: 15, 22: 16, 23: 16}

# Sanitizers run on optimised code, the same RelWithDebInfo (-O2 -g) the
# plain presets use: the runtimes are designed for -O1 and up, the shipped
# kernels only exist under optimisation (the xsimd/std::simd layers are
# call chains at -O0, and MSan's origin tracking multiplies that), and
# optimiser-dependent bugs need the optimiser to show. -fno-omit-frame-
# pointer and -fno-optimize-sibling-calls keep the traces honest. Coverage
# stays Debug: it wants unoptimised control flow.
INSTRUMENTATIONS = {
    "asan": {"sanitizers": ["address", "undefined"], "build_type": "RelWithDebInfo"},
    "tsan": {"sanitizers": ["thread"], "build_type": "RelWithDebInfo"},
    "msan": {"sanitizers": ["memory"], "build_type": "RelWithDebInfo", "clang_only": True},
    "fuzzer": {"sanitizers": ["fuzzer", "address", "undefined"], "clang_only": True},
    "coverage": {"coverage": "auto", "build_type": "Debug"},
}
# ---------------------------------------------------------------------------

HEADER = """# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# {desc}
#
#   cmake -S . -B build/{name} -G Ninja \\
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/{name}.cmake
"""


def render(name: str, desc: str, tc: dict[str, object]) -> str:
    lines = [HEADER.format(name=name, desc=desc), ""]
    for key, value in tc.items():
        if value is None or value == "":
            continue
        if isinstance(value, list):
            joined = " ".join(str(v) for v in value)
            lines.append(f"set(TC_{key} {joined})")
        else:
            lines.append(f'set(TC_{key} "{value}")')
    lines.append("")
    lines.append('include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")')
    lines.append("")
    return "\n".join(lines)


def base_configs() -> list[tuple[str, str, dict]]:
    """(name, description, TC_* dict) for every plain compiler/standard combo."""
    out = []

    for v in GCC_VERSIONS:
        for std in GCC_STDS.get(v, []):
            out.append((
                f"{HOST_OS}-gcc{v}-cxx{std}",
                f"GCC {v} with libstdc++ {v}, C++{std}",
                {
                    "C_COMPILER": f"gcc-{v}",
                    "CXX_COMPILER": f"g++-{v}",
                    "CXX_STANDARD": std,
                    # No LINKER: mold 2.40 cannot parse GCC 16 trunk's
                    # libatomic_asneeded.so INPUT(AS_NEEDED(...)) script, so
                    # GCC stays on its default (bfd), which also keeps
                    # GCC-LTO viable.
                    "DEFAULT_BUILD_TYPE": "RelWithDebInfo",
                },
            ))

    # The libc++ flavor rides the SYSTEM libc++, and Ubuntu's libc++-X-dev
    # packages conflict across versions (one unversioned /usr/include/c++/v1
    # per container), so every clang here parses the NEWEST clang's libc++
    # headers. That works within a small version skew (clang 20 vs libc++ 22
    # is fine) but clang 18 cannot parse libc++-22's headers; older clangs
    # get their coverage from the pinned-libstdcxx variant below instead.
    LIBCXX_MIN_CLANG = 20
    for v in CLANG_VERSIONS:
        if v < LIBCXX_MIN_CLANG:
            continue
        for std in CLANG_STDS.get(v, []):
            out.append((
                f"{HOST_OS}-clang{v}-cxx{std}",
                f"Clang {v} with libc++ (system), C++{std}",
                {
                    "C_COMPILER": f"clang-{v}",
                    "CXX_COMPILER": f"clang++-{v}",
                    "STDLIB": "libc++",
                    "CXX_STANDARD": std,
                    "LINKER": f"lld-{v}",
                    "DEFAULT_BUILD_TYPE": "RelWithDebInfo",
                },
            ))

    # Clang against libstdc++ instead, pinned to a GCC of a compatible vintage.
    # Pairing a Clang with the newest GCC's libstdc++ is the usual way this
    # breaks, so the pin is not optional in a multi-compiler image.
    for v in CLANG_VERSIONS:
        target = CLANG_TO_GCC.get(v, v - 6)
        candidates = [g for g in GCC_VERSIONS if g <= target]
        gcc_pin = max(candidates) if candidates else min(GCC_VERSIONS)
        std = min(CLANG_STDS.get(v, [20]))
        out.append((
            f"{HOST_OS}-clang{v}-cxx{std}-libstdcxx",
            f"Clang {v} against libstdc++ {gcc_pin} (pinned), C++{std}",
            {
                "C_COMPILER": f"clang-{v}",
                "CXX_COMPILER": f"clang++-{v}",
                "STDLIB": "libstdc++",
                "GCC_INSTALL_DIR": f"/usr/lib/gcc/{GCC_TRIPLE}/{gcc_pin}",
                "CXX_STANDARD": std,
                "LINKER": f"lld-{v}",
                "DEFAULT_BUILD_TYPE": "RelWithDebInfo",
            },
        ))

    # Post-C++26 experiment: CMake has no cxx_std_29, so pass the flag raw.
    out.append((
        f"{HOST_OS}-clang{DEFAULT_CLANG}-cxx2c",
        f"Clang {DEFAULT_CLANG} with libc++, experimental -std=c++2c "
        "(post-C++26 working draft)",
        {
            "C_COMPILER": f"clang-{DEFAULT_CLANG}",
            "CXX_COMPILER": f"clang++-{DEFAULT_CLANG}",
            "STDLIB": "libc++",
            "CXX_STANDARD_RAW": "c++2c",
            "LINKER": f"lld-{DEFAULT_CLANG}",
            "DEFAULT_BUILD_TYPE": "RelWithDebInfo",
        },
    ))

    return out


def instrumented(bases: list[tuple[str, str, dict]], everywhere: bool):
    out = []
    if everywhere:
        targets = bases
    else:
        wanted = {
            f"{HOST_OS}-gcc{DEFAULT_GCC}-cxx{max(GCC_STDS[DEFAULT_GCC])}",
            f"{HOST_OS}-clang{DEFAULT_CLANG}-cxx{max(CLANG_STDS[DEFAULT_CLANG])}",
        }
        targets = [b for b in bases if b[0] in wanted]

    for name, desc, tc in targets:
        is_clang = "clang" in tc["CXX_COMPILER"]
        for inst, spec in INSTRUMENTATIONS.items():
            if spec.get("clang_only") and not is_clang:
                continue
            new = dict(tc)
            if "sanitizers" in spec:
                new["SANITIZERS"] = spec["sanitizers"]
            if "coverage" in spec:
                new["COVERAGE"] = "llvm" if is_clang else "gcov"
            if "build_type" in spec:
                new["DEFAULT_BUILD_TYPE"] = spec["build_type"]
            if inst == "msan":
                # An uninstrumented libc++ makes MSan report other people's
                # uninitialised memory, so point it at the instrumented build.
                new["MSAN_LIBCXX_PREFIX"] = "/opt/libcxx-msan"
            out.append((f"{name}-{inst}", f"{desc} + {inst}", new))
    return out


def main() -> int:
    global HOST_OS
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=OUTDIR_DEFAULT)
    ap.add_argument("--os", default=HOST_OS,
                    help="OS component of the generated names "
                         "(default: %(default)s; the macOS and Windows "
                         "toolchains are hand-written, not generated)")
    ap.add_argument("--all", action="store_true",
                    help="instrument every compiler/standard combo, not just the newest")
    ap.add_argument("--list", action="store_true", help="print names and exit")
    ap.add_argument("--presets", action="store_true",
                    help="also write CMakePresets-toolchains.json alongside")
    args = ap.parse_args()
    HOST_OS = args.os

    bases = base_configs()
    configs = bases + instrumented(bases, args.all)

    if args.list:
        for name, desc, _ in configs:
            print(f"{name:38s} {desc}")
        print(f"\n{len(configs)} configurations")
        return 0

    os.makedirs(args.out, exist_ok=True)
    if not os.path.exists(os.path.join(args.out, "common.cmake")):
        print(f"warning: common.cmake not found in {args.out}", file=sys.stderr)

    for name, desc, tc in configs:
        path = os.path.join(args.out, f"{name}.cmake")
        with open(path, "w") as fh:
            fh.write(render(name, desc, tc))
    print(f"wrote {len(configs)} toolchain files to {args.out}")

    if args.presets:
        rel = os.path.relpath(args.out, REPO).replace(os.sep, "/")
        presets = {
            "version": 6,
            "configurePresets": [
                {
                    "name": name,
                    "displayName": desc,
                    "generator": "Ninja",
                    "binaryDir": "${sourceDir}/build/" + name,
                    "toolchainFile": "${sourceDir}/" + f"{rel}/{name}.cmake",
                    "cacheVariables": {
                        "CMAKE_BUILD_TYPE": (
                            "Debug" if "coverage" in name else "RelWithDebInfo")
                    },
                }
                for name, desc, _ in configs
            ],
            "buildPresets": [{"name": n, "configurePreset": n} for n, _, _ in configs],
        }
        path = os.path.join(REPO, "CMakePresets-toolchains.json")
        with open(path, "w") as fh:
            json.dump(presets, fh, indent=2)
            fh.write("\n")
        print(f"wrote {path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
