#!/usr/bin/env python3
"""Turn the official BLAKE3 test_vectors.json into a C++ header.

The JSON is committed verbatim under tests/vectors/ for provenance; this
script runs at build time (see tests/CMakeLists.txt) so the tests need no
JSON parser. Each case's input is input_len bytes of the repeating pattern
0,1,...,250,0,1,... and the hex strings are 131 bytes of XOF output; plain
32-byte hashing compares against the first 64 hex chars.
"""

from __future__ import annotations

import json
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <test_vectors.json> <out.hpp>", file=sys.stderr)
        return 2

    with open(sys.argv[1]) as fh:
        data = json.load(fh)

    lines = [
        "// GENERATED by tools/gen-test-vectors.py from tests/vectors/test_vectors.json",
        "// -- do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace blake3pp::testvec {",
        "",
        "struct test_case {",
        "  std::size_t input_len;",
        "  const char* hash;        // 131-byte XOF as hex; first 64 chars = 32-byte hash",
        "  const char* keyed_hash;",
        "  const char* derive_key;",
        "};",
        "",
        f'inline constexpr const char key[] = {json.dumps(data["key"])};',
        f'inline constexpr const char context[] = {json.dumps(data["context_string"])};',
        "",
        "inline constexpr test_case cases[] = {",
    ]
    for c in data["cases"]:
        lines.append(
            f'    {{{c["input_len"]}, "{c["hash"]}", "{c["keyed_hash"]}", '
            f'"{c["derive_key"]}"}},'
        )
    lines += [
        "};",
        "",
        "}  // namespace blake3pp::testvec",
        "",
    ]

    with open(sys.argv[2], "w") as fh:
        fh.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
