# Compiles src/kernel/kernel.cpp once per architecture variant.
#
# Every variant is an OBJECT library with its own -m flags and its own
# namespace, injected as -DBLAKE3PP_ARCH_NS=<name>. Distinct namespaces mean
# distinct mangled symbols, so LTO can never fold an AVX2-compiled function
# into the scalar fallback path (or vice versa); the ODR is respected by
# construction instead of by luck. IPO is additionally forced off on kernel
# objects so no cross-TU inlining can leak native host instructions out of a
# variant's translation unit.
#
# SIMD types must never appear in a kernel's exported signatures: their ABI
# changes with the -m flags of the TU. The boundary API in
# src/kernel/kernel.hpp is flat pointers only.

include_guard(GLOBAL)

function(blake3pp_add_kernel ns)
  cmake_parse_arguments(PARSE_ARGV 1 AK "FORCE_SCALAR" "" "ARCH_FLAGS")

  set(tgt "blake3pp_kernel_${ns}")
  add_library(${tgt} OBJECT "${PROJECT_SOURCE_DIR}/src/kernel/kernel.cpp")
  target_compile_definitions(${tgt} PRIVATE "BLAKE3PP_ARCH_NS=${ns}")
  if(AK_FORCE_SCALAR)
    # The scalar fallback must be genuinely scalar: without this, the simd
    # facade would still pick the baseline vector width (SSE2 on x86-64).
    target_compile_definitions(${tgt} PRIVATE "BLAKE3PP_FORCE_SCALAR=1")
  endif()
  if(AK_ARCH_FLAGS)
    target_compile_options(${tgt} PRIVATE ${AK_ARCH_FLAGS})
  endif()
  # The kernels are the hot loop and measurably faster at -O3 (GCC's
  # std::simd path is ~2x slower at -O2). Applied only to optimized configs
  # so Debug/sanitizer builds keep their debuggability; appended after the
  # config flags, so it wins over RelWithDebInfo's -O2. MSVC-frontend
  # spelling: cl has no /O3 (Release's /O2 is already its ceiling);
  # clang-cl takes the flag through its /clang: passthrough.
  if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      target_compile_options(${tgt} PRIVATE
        "$<$<CONFIG:Release,RelWithDebInfo>:/clang:-O3>")
    else()
      # cl's default inlining budget (/Ob2) gives up on the facade's
      # template chains (measured: the sse42 kernel came out as a call
      # soup with 12 vector adds total). /Ob3 raises the budget.
      target_compile_options(${tgt} PRIVATE
        "$<$<CONFIG:Release,RelWithDebInfo>:/Ob3>")
    endif()
  else()
    target_compile_options(${tgt} PRIVATE
      "$<$<CONFIG:Release,RelWithDebInfo>:-O3>")
  endif()
  # GCC's post-RA scheduler measurably hurts this register-saturated kernel
  # (+6% from disabling it, 3/3 paired runs on znver3): with ~32 live vector
  # values on 16 registers, its static ILP-driven reordering only disturbs
  # the dataflow order the out-of-order core exploits natively. Clang is the
  # opposite: disabling its (pressure-aware) MachineScheduler costs ~10%,
  # so it stays on. Measured, not assumed.
  target_compile_options(${tgt} PRIVATE
    "$<$<CXX_COMPILER_ID:GNU>:-fno-schedule-insns2>")
  # Experimentation hook: extra flags for kernel TUs only (scheduler knobs,
  # tuning trials). Semicolon-separated list; empty by default.
  if(BLAKE3PP_KERNEL_EXTRA_FLAGS)
    target_compile_options(${tgt} PRIVATE ${BLAKE3PP_KERNEL_EXTRA_FLAGS})
  endif()
  target_include_directories(${tgt} PRIVATE
    "${PROJECT_SOURCE_DIR}/src"
    "${PROJECT_SOURCE_DIR}/include")
  target_compile_features(${tgt} PRIVATE cxx_std_20)
  target_link_libraries(${tgt} PRIVATE blake3pp::features)
  set_target_properties(${tgt} PROPERTIES
    INTERPROCEDURAL_OPTIMIZATION OFF
    POSITION_INDEPENDENT_CODE ON)

  set_property(GLOBAL APPEND PROPERTY BLAKE3PP_KERNELS "${ns}")
endfunction()

# Attaches every registered kernel's objects to <target> and generates the
# kernel registry, an X-macro list of exactly the variants in THIS binary.
# dispatch.cpp expands it into extern declarations and its dispatch/query
# tables, so the blake3pp_add_kernel() calls are the single source of
# truth: registering a variant here is all it takes for it to appear in
# dispatch, compiled_arches() and available_arches().
function(blake3pp_target_link_kernels target)
  get_property(kernels GLOBAL PROPERTY BLAKE3PP_KERNELS)
  set(registry "// GENERATED by cmake/ArchKernels.cmake -- do not edit.\n")
  foreach(ns IN LISTS kernels)
    target_sources(${target} PRIVATE "$<TARGET_OBJECTS:blake3pp_kernel_${ns}>")
    string(APPEND registry "BLAKE3PP_KERNEL(${ns})\n")
  endforeach()
  # file(CONFIGURE) only rewrites on content change, so dispatch.cpp is not
  # recompiled by every reconfigure.
  file(CONFIGURE
    OUTPUT "${CMAKE_BINARY_DIR}/blake3pp_generated/blake3pp_kernel_registry.inc"
    CONTENT "${registry}" @ONLY)
  target_include_directories(${target} PRIVATE
    "${CMAKE_BINARY_DIR}/blake3pp_generated")
endfunction()
