# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# Clang 18 against libstdc++ 14 (pinned), C++20
#
#   cmake -S . -B build/clang18-c20-libstdcxx -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/clang18-c20-libstdcxx.cmake


set(TC_C_COMPILER "clang-18")
set(TC_CXX_COMPILER "clang++-18")
set(TC_STDLIB "libstdc++")
set(TC_GCC_INSTALL_DIR "/usr/lib/gcc/x86_64-linux-gnu/14")
set(TC_CXX_STANDARD "20")
set(TC_LINKER "lld-18")
set(TC_DEFAULT_BUILD_TYPE "RelWithDebInfo")

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
