# GENERATED by tools/gen-toolchains.py -- edit that script, not this file.
#
# GCC 16 with libstdc++ 16, C++26 + asan
#
#   cmake -S . -B build/gcc16-c26-asan -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/gcc16-c26-asan.cmake


set(TC_C_COMPILER "gcc-16")
set(TC_CXX_COMPILER "g++-16")
set(TC_CXX_STANDARD "26")
set(TC_LINKER "mold")
set(TC_DEFAULT_BUILD_TYPE "Debug")
set(TC_SANITIZERS address undefined)

include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
