# Build-time version stamp (run via cmake -P, never include()d).
#
# Ladder, most specific first:
#   HEAD exactly at a version tag   ->  <tag-version>+g<hash>          (release)
#   any other commit                ->  <last-tag minor+1>.0-dev-<hash>
#   no version tag in history       ->  <FALLBACK_VERSION>-dev-<hash>
#   no git / no .git (tarball, the  ->  <FALLBACK_VERSION>
#     Windows tar-over-ssh sync)
# A modified work tree appends ".dirty" to the hash. Tags may be "1.2.3" or
# "v1.2.3". "Tagged implies main branch" is a process rule, not checked
# here; detached and shallow checkouts can't answer branch questions
# reliably.
#
# Under cmake-re the source tree is a mirror whose HEAD may be a synthetic
# "[tipi.build uncommited changes]" commit carrying the checkout's
# uncommitted files, with a new hash every sync. The stamp looks through
# it: the hash and the tag questions go to its parent (the real commit)
# and the tree counts as dirty, which is what it is. Without this every
# remote build carried a hash nobody can look up, and a no-change rerun
# on a restored mirror rebuilt everything downstream of the stamp.
#
# Inputs: SOURCE_DIR, OUTPUT_FILE, FALLBACK_VERSION.
# The output header is written through copy_if_different, so its timestamp
# only moves when the version string actually changes: a no-change build
# stays a no-op and only one TU recompiles when it doesn't.

cmake_minimum_required(VERSION 3.28)

set(_version "${FALLBACK_VERSION}")

find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
  set(_ref HEAD)
  set(_dirty "")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" log -1 --format=%s HEAD
    OUTPUT_VARIABLE _subject OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _subject_rc ERROR_QUIET)
  if(_subject_rc EQUAL 0
     AND _subject MATCHES "^\\[tipi\\.build uncommited changes\\]")
    set(_ref "HEAD~1")
    set(_dirty ".dirty")
  endif()

  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 "${_ref}"
    OUTPUT_VARIABLE _hash OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _rc ERROR_QUIET)
  if(_rc EQUAL 0)
    # Porcelain-based dirty check: `describe --dirty` trusts the stat cache,
    # which lies on bind mounts; this one refreshes.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain -uno
      OUTPUT_VARIABLE _status ERROR_QUIET)
    if(NOT _status STREQUAL "")
      set(_dirty ".dirty")
    endif()

    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" describe --tags
              --exact-match --match "v[0-9]*" --match "[0-9]*" "${_ref}"
      OUTPUT_VARIABLE _exact_tag OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE _exact_rc ERROR_QUIET)

    if(_exact_rc EQUAL 0 AND _exact_tag MATCHES "^v?([0-9]+\\.[0-9]+\\.[0-9]+)$")
      set(_version "${CMAKE_MATCH_1}+g${_hash}${_dirty}")
    else()
      execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" describe --tags
                --abbrev=0 --match "v[0-9]*" --match "[0-9]*" "${_ref}"
        OUTPUT_VARIABLE _last_tag OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _last_rc ERROR_QUIET)
      if(_last_rc EQUAL 0
         AND _last_tag MATCHES "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
        math(EXPR _next_minor "${CMAKE_MATCH_2} + 1")
        set(_version "${CMAKE_MATCH_1}.${_next_minor}.0-dev-${_hash}${_dirty}")
      else()
        set(_version "${FALLBACK_VERSION}-dev-${_hash}${_dirty}")
      endif()
    endif()
  endif()
endif()

set(_content "// Generated by cmake/GitVersionStamp.cmake at build time; do not edit.
#pragma once
#define BLAKE3PP_STAMPED_VERSION \"${_version}\"
")

file(WRITE "${OUTPUT_FILE}.tmp" "${_content}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}")
file(REMOVE "${OUTPUT_FILE}.tmp")
