# Cross toolchain: s390x Linux, GCC 15, C++23. The project's first
# BIG-ENDIAN target. Executables run through qemu-user
# (CROSSCOMPILING_EMULATOR); QEMU_CPU selects the machine generation
# (qemu's default/max carries the z14 vector-enhancements facility, and
# an older model runs the scalar fallback).
#
# Hand-written (not generated by tools/gen-toolchains.py, which covers
# the native-compiler matrix).

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR s390x)

set(CMAKE_C_COMPILER s390x-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER s390x-linux-gnu-g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
# Baseline z13 (vector facility, no enhancements) for everything except
# the vxe kernel, which cmake/KernelVariants.cmake compiles with its own
# -march=z14. Ubuntu 26.04's s390x GCC defaults to arch13 (z15), which
# would let any TU, the dependencies included, emit z14/z15 instructions
# the dispatch verdict does not gate; the no-vxe fallback config in
# tools/ci-test.sh (qemu max,vxeh=off) is only a legitimate target for
# the project's own code with this pin. The sysroot's own libraries stay
# whatever the distro built them for.
set(CMAKE_C_FLAGS_INIT "-march=z13")
set(CMAKE_CXX_FLAGS_INIT "-march=z13")

# Resolved to an absolute path: under cmake-re the test launcher
# (tipi-test-driver) execve's the command literally, no PATH search.
find_program(BLAKE3PP_QEMU NAMES qemu-s390x REQUIRED NO_CACHE)
set(CMAKE_CROSSCOMPILING_EMULATOR "${BLAKE3PP_QEMU};-L;/usr/s390x-linux-gnu")

set(CMAKE_FIND_ROOT_PATH /usr/s390x-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Same reasoning as riscv64/ppc64le: the vxe kernel pins xsimd; keep the
# base build and the introspection consistent with it.
set(BLAKE3PP_SIMD_PROVIDER "xsimd" CACHE STRING
  "simd provider (set by the s390x toolchain)")
