#pragma once

#include <bit>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <format>
#include <string>
#include <thread>
#include <utility>
#include <version>

#include <CLI/CLI.hpp>
#include <blake3pp/parallel.hpp>

#if defined(__cpp_lib_print)
#include <print>
#endif

#if defined(BLAKE3PP_EXECUTION_STDEXEC)
#include <optional>

#include <exec/static_thread_pool.hpp>
#endif

#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <fcntl.h>
#include <io.h>
#include <windows.h>
#elif defined(__linux__)
#include <sys/syscall.h>
#include <unistd.h>
#endif

namespace b3tool {

// The project's provider pattern in miniature: std::print where the
// standard library ships it (C++23), a std::format shim on the C++20
// toolchains; same source either way.
#if defined(__cpp_lib_print)
using std::print;
using std::println;
#else
template <class... Args>
void print(std::FILE* stream, std::format_string<Args...> fmt,
           Args&&... args) {
  std::fputs(std::format(fmt, std::forward<Args>(args)...).c_str(), stream);
}

template <class... Args>
void println(std::FILE* stream, std::format_string<Args...> fmt,
             Args&&... args) {
  print(stream, fmt, std::forward<Args>(args)...);
  std::fputc('\n', stream);
}
#endif

// Exit status convention shared by the tools, after the coreutils
// checksum programs: 1 when the work itself failed (a file could not be
// read, a checksum did not match), 2 when the invocation was wrong
// (unusable option values, an input that cannot be opened before any
// work starts).
inline constexpr int exit_failure = 1;
inline constexpr int exit_usage = 2;

// Chunking for byte streams that are not the file pipeline: stdin into
// a hasher, generated bytes out to stdout.
inline constexpr std::size_t stream_buffer_bytes = std::size_t{1} << 20;

// The --threads default: every hardware thread, and never 0 (which
// hardware_concurrency() may report when it cannot tell).
[[nodiscard]] inline unsigned default_threads() noexcept {
  const unsigned n = std::thread::hardware_concurrency();
  return n == 0 ? 1 : n;
}

// The --threads option, identical across the tools: `what` names the
// threads in the help text ("compute threads", "generator threads");
// 1 means sequential and 0 is rejected with a message that says so.
inline CLI::Option* add_threads_option(CLI::App& app, unsigned& threads,
                                       const char* what) {
  static const CLI::Validator at_least_one(
      [](std::string& value) {
        long long n = 0;
        const bool numeric = CLI::detail::lexical_cast(value, n);
        return numeric && n < 1
                   ? std::string{"must be at least 1 (1 = sequential)"}
                   : std::string{};  // non-numbers fail the UINT conversion
      },
      "THREADS");
  return app
      .add_option("--threads", threads,
                  std::format("{} (1 = sequential; default: all)", what))
      ->check(at_least_one)
      ->capture_default_str();
}

// Windows opens std streams in text mode, which translates line endings,
// fatal for raw hash input and generated byte streams. POSIX has no such
// distinction; this is a no-op there.
inline void set_binary_std_streams() noexcept {
#if defined(_WIN32)
  _setmode(_fileno(stdin), _O_BINARY);
  _setmode(_fileno(stdout), _O_BINARY);
#endif
}

// --threads, resolved to a scheduler. Both tools share the convention:
// the default is default_threads(), 1 means sequential, 0 is rejected
// by the parser.
//
// stdexec honors the count exactly (a pool of that size); the other
// providers use the process-wide parallel scheduler, where any count > 1
// means "parallel" and the exact number is the provider's business. That
// difference is the whole reason this type exists, and it collapses to one
// non-template signature because of a type coincidence worth knowing:
// under stdexec blake3pp::parallel_scheduler_t IS the scheduler type of an
// exec::static_thread_pool (see include/blake3pp/parallel.hpp), so the
// owned pool and the process-wide one return the same type here.
class compute_pool {
 public:
  explicit compute_pool(unsigned threads) : threads_(threads) {
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
    if (threads > 1) {
      pool_.emplace(threads);
    }
#endif
  }

  // Whether work should be offloaded at all.
  [[nodiscard]] bool parallel() const noexcept { return threads_ > 1; }

  // Precondition: parallel(). Under stdexec this hands out the owned pool's
  // scheduler, which exists exactly when parallel() is true.
  [[nodiscard]] blake3pp::parallel_scheduler_t scheduler() {
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
    return pool_.value().get_scheduler();
#else
    return blake3pp::get_parallel_scheduler();
#endif
  }

 private:
  unsigned threads_;
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
  std::optional<exec::static_thread_pool> pool_;
#endif
};

// --- Thread placement -------------------------------------------------------
// Heterogeneous machines (phone big.LITTLE, M-series P/E) migrate a busy
// thread between core CLASSES mid-run, so single-thread rows from the same
// run are not automatically comparable (measured as a 21% phantom on an
// Exynos 2600, where the row that happened to run last inherited the prime
// core). These helpers make placement visible (current_cpu per row) and
// controllable (--pin).
//
// Linux goes through raw syscalls rather than sched_setaffinity()/
// sched_getcpu(): the libc wrappers hide behind _GNU_SOURCE, which musl
// does not define for us under every frontend we ship, and a header is the
// wrong place to define it. Same visible-moving-parts spirit as the
// io_uring and hwprobe call sites.

// Which CPU the calling thread is on right now, -1 where the OS offers no
// answer (macOS has no API for it). Printed per bench row: the Exynos
// failure was not "could not pin" but "did not know the rows ran on
// different cores"; a reader of someone else's bench output has no other
// way to see it.
inline int current_cpu() noexcept {
#if defined(__linux__)
  unsigned cpu = 0;
  return ::syscall(SYS_getcpu, &cpu, nullptr, nullptr) == 0
             ? static_cast<int>(cpu)
             : -1;
#elif defined(_WIN32)
  return static_cast<int>(::GetCurrentProcessorNumber());
#else
  return -1;
#endif
}

// Pins the CALLING thread and restores the startup mask on request. The
// restore MUST happen before any thread pool is constructed: on Linux new
// threads inherit the creating thread's affinity, so a leaked pin silently
// turns an N-thread pool into a one-core pool. (Windows threads inherit
// the process mask instead; the restore is harmless there.)
class thread_pin {
 public:
#if defined(__linux__)
  // 1024 CPUs, the same ceiling glibc's cpu_set_t defaults to.
  struct mask {
    unsigned long bits[128 / sizeof(unsigned long)] = {};
  };

  thread_pin() noexcept {
    saved_ok_ =
        ::syscall(SYS_sched_getaffinity, 0, sizeof(saved_), &saved_) > 0;
  }

  [[nodiscard]] bool pin(int cpu) noexcept {
    if (cpu < 0 || static_cast<unsigned>(cpu) >= sizeof(mask) * 8) {
      return false;
    }
    mask m;
    m.bits[static_cast<unsigned>(cpu) / (sizeof(unsigned long) * 8)] |=
        1ul << (static_cast<unsigned>(cpu) % (sizeof(unsigned long) * 8));
    return ::syscall(SYS_sched_setaffinity, 0, sizeof(m), &m) == 0;
  }

  void restore() noexcept {
    if (saved_ok_) {
      ::syscall(SYS_sched_setaffinity, 0, sizeof(saved_), &saved_);
    }
  }

 private:
  mask saved_{};
  bool saved_ok_ = false;
#elif defined(_WIN32)
  thread_pin() noexcept {
    DWORD_PTR sys = 0;
    saved_ok_ = ::GetProcessAffinityMask(::GetCurrentProcess(), &saved_,
                                         &sys) != 0;
  }

  [[nodiscard]] bool pin(int cpu) noexcept {
    if (cpu < 0 || cpu >= static_cast<int>(sizeof(DWORD_PTR) * 8)) {
      return false;
    }
    return ::SetThreadAffinityMask(::GetCurrentThread(),
                                   DWORD_PTR{1} << cpu) != 0;
  }

  void restore() noexcept {
    if (saved_ok_) {
      ::SetThreadAffinityMask(::GetCurrentThread(), saved_);
    }
  }

 private:
  DWORD_PTR saved_ = 0;
  bool saved_ok_ = false;
#else
  thread_pin() noexcept = default;
  [[nodiscard]] static bool pin(int) noexcept { return false; }
  static void restore() noexcept {}
#endif

 public:
  static constexpr bool supported() noexcept {
#if defined(__linux__) || defined(_WIN32)
    return true;
#else
    return false;
#endif
  }
};

// How many CPUs the calling thread may run on, -1 if unknowable. Printed
// in the parallel-engine header so a leaked --pin (or an Android cpuset
// hiding cores) is visible in the output instead of silently shrinking
// an "N-thread" number.
inline int affinity_cpu_count() noexcept {
#if defined(__linux__)
  thread_pin::mask m;
  if (::syscall(SYS_sched_getaffinity, 0, sizeof(m), &m) <= 0) {
    return -1;
  }
  int n = 0;
  for (const unsigned long w : m.bits) {
    n += std::popcount(w);
  }
  return n;
#elif defined(_WIN32)
  DWORD_PTR proc = 0;
  DWORD_PTR sys = 0;
  if (!::GetProcessAffinityMask(::GetCurrentProcess(), &proc, &sys)) {
    return -1;
  }
  return std::popcount(static_cast<std::uint64_t>(proc));
#else
  return -1;
#endif
}

// --- Measurement ------------------------------------------------------------
// The benchmarks are deliberately framework-free (pair them with hyperfine
// when process-level statistics are wanted), but "best of N, warm up once,
// idle between measurements" is a house convention rather than something
// each program should reinvent.

// Best-of-`reps` wall-clock seconds for fn: the interesting number for a
// throughput ceiling, since interference only ever slows a run down. With
// `warmup`, one extra uncounted repetition runs first to pay for cold
// caches, lazy page faults and first-touch allocation.
template <class F>
[[nodiscard]] double best_seconds(int reps, bool warmup, F&& fn) {
  double best = 1e100;
  const int first = warmup ? -1 : 0;
  for (int r = first; r < reps; ++r) {
    const auto t0 = std::chrono::steady_clock::now();
    fn();
    const auto t1 = std::chrono::steady_clock::now();
    const double s = std::chrono::duration<double>(t1 - t0).count();
    if (r >= 0 && s < best) {
      best = s;
    }
  }
  return best;
}

[[nodiscard]] inline double gib_per_s(std::size_t bytes,
                                      double seconds) noexcept {
  return static_cast<double>(bytes) / seconds / (1024.0 * 1024.0 * 1024.0);
}

// Laptops throttle: run variants back to back and each one measures the
// previous one's heat (observed: ~20% swing on identical code). Call this
// between measurements to idle. `skip_first` starts measuring immediately
// when nothing has run yet; seconds of 0 disables the wait entirely.
class cooldown {
 public:
  explicit cooldown(double seconds, bool skip_first = true)
      : seconds_(seconds), pending_(!skip_first) {}

  void operator()() {
    if (!pending_) {
      pending_ = true;
      return;
    }
    if (seconds_ > 0) {
      std::fflush(stdout);
      std::this_thread::sleep_for(std::chrono::duration<double>(seconds_));
    }
  }

 private:
  double seconds_;
  bool pending_;
};

}  // namespace b3tool
