#pragma once

#include <chrono>
#include <cstddef>
#include <cstdio>
#include <format>
#include <thread>
#include <utility>
#include <version>

#include <blake3pp/parallel.hpp>

#if defined(__cpp_lib_print)
#include <print>
#endif

#if defined(BLAKE3PP_EXECUTION_STDEXEC)
#include <optional>

#include <exec/static_thread_pool.hpp>
#endif

#if defined(_WIN32)
#include <fcntl.h>
#include <io.h>
#endif

namespace b3tool {

// The project's provider pattern in miniature: std::print where the
// standard library ships it (C++23), a std::format shim on the C++20
// toolchains; same source either way.
#if defined(__cpp_lib_print)
using std::print;
using std::println;
#else
template <class... Args>
void print(std::FILE* stream, std::format_string<Args...> fmt,
           Args&&... args) {
  std::fputs(std::format(fmt, std::forward<Args>(args)...).c_str(), stream);
}

template <class... Args>
void println(std::FILE* stream, std::format_string<Args...> fmt,
             Args&&... args) {
  print(stream, fmt, std::forward<Args>(args)...);
  std::fputc('\n', stream);
}
#endif

// Windows opens std streams in text mode, which translates line endings,
// fatal for raw hash input and generated byte streams. POSIX has no such
// distinction; this is a no-op there.
inline void set_binary_std_streams() noexcept {
#if defined(_WIN32)
  _setmode(_fileno(stdin), _O_BINARY);
  _setmode(_fileno(stdout), _O_BINARY);
#endif
}

// --threads, resolved to a scheduler.
//
// stdexec honors the count exactly (a pool of that size); the other
// providers use the process-wide parallel scheduler, where any count > 1
// means "parallel" and the exact number is the provider's business. That
// difference is the whole reason this type exists, and it collapses to one
// non-template signature because of a type coincidence worth knowing:
// under stdexec blake3pp::parallel_scheduler_t IS the scheduler type of an
// exec::static_thread_pool (see include/blake3pp/parallel.hpp), so the
// owned pool and the process-wide one return the same type here.
class compute_pool {
 public:
  explicit compute_pool(unsigned threads) : threads_(threads) {
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
    if (threads > 1) {
      pool_.emplace(threads);
    }
#endif
  }

  // Whether work should be offloaded at all.
  [[nodiscard]] bool parallel() const noexcept { return threads_ > 1; }

  // Precondition: parallel(). Under stdexec this hands out the owned pool's
  // scheduler, which exists exactly when parallel() is true.
  [[nodiscard]] blake3pp::parallel_scheduler_t scheduler() {
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
    return pool_.value().get_scheduler();
#else
    return blake3pp::get_parallel_scheduler();
#endif
  }

 private:
  unsigned threads_;
#if defined(BLAKE3PP_EXECUTION_STDEXEC)
  std::optional<exec::static_thread_pool> pool_;
#endif
};

// --- Measurement ------------------------------------------------------------
// The benchmarks are deliberately framework-free (pair them with hyperfine
// when process-level statistics are wanted), but "best of N, warm up once,
// idle between measurements" is a house convention rather than something
// each program should reinvent.

// Best-of-`reps` wall-clock seconds for fn: the interesting number for a
// throughput ceiling, since interference only ever slows a run down. With
// `warmup`, one extra uncounted repetition runs first to pay for cold
// caches, lazy page faults and first-touch allocation.
template <class F>
[[nodiscard]] double best_seconds(int reps, bool warmup, F&& fn) {
  double best = 1e100;
  const int first = warmup ? -1 : 0;
  for (int r = first; r < reps; ++r) {
    const auto t0 = std::chrono::steady_clock::now();
    fn();
    const auto t1 = std::chrono::steady_clock::now();
    const double s = std::chrono::duration<double>(t1 - t0).count();
    if (r >= 0 && s < best) {
      best = s;
    }
  }
  return best;
}

[[nodiscard]] inline double gib_per_s(std::size_t bytes,
                                      double seconds) noexcept {
  return static_cast<double>(bytes) / seconds / (1024.0 * 1024.0 * 1024.0);
}

// Laptops throttle: run variants back to back and each one measures the
// previous one's heat (observed: ~20% swing on identical code). Call this
// between measurements to idle. `skip_first` starts measuring immediately
// when nothing has run yet; seconds of 0 disables the wait entirely.
class cooldown {
 public:
  explicit cooldown(double seconds, bool skip_first = true)
      : seconds_(seconds), pending_(!skip_first) {}

  void operator()() {
    if (!pending_) {
      pending_ = true;
      return;
    }
    if (seconds_ > 0) {
      std::fflush(stdout);
      std::this_thread::sleep_for(std::chrono::duration<double>(seconds_));
    }
  }

 private:
  double seconds_;
  bool pending_;
};

}  // namespace b3tool
